# -*- coding: utf-8 -*-
"""sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cCgonYH8jz2MOWmhijJ7BQ0PYVoMP5x
"""

import pandas as pd
import numpy as np

dataset=pd.read_csv("/content/sales_data.csv")

dataset

dataset.head()

"""**Shape of the dataset**"""

dataset.shape

columns=dataset.columns.tolist()

"""**List of columns**"""

print(columns)

"""**Null values or missing values in each column**"""

dataset.isnull().sum()

"""No null values present in any columns"""

dataset["total_sales"]=dataset["Quantity"]*dataset["Price"]
dataset.head()

"""**About Dataset**"""

dataset.describe()

"""**deleting the column**"""

dataset.drop(columns="total_sales",axis=1)

"""**Average sales for each product**"""

dataset.groupby("Product")["Total_Sales"].mean()

"""**Total no of products sold for each Region**"""

dataset.groupby("Region")["Product"].count()

"""**Total Quantity sold in each Region**"""

dataset.groupby("Region")["Quantity"].sum()

dataset.head()

"""**Highest price of each prodct**"""

dataset.groupby("Product")["Price"].max()

"""**Lowest Price of each Product**"""

dataset.groupby("Product")["Price"].min()

"""**Average cost for each product**"""

dataset.groupby("Product")["Price"].mean()

"""**no of products for each category**"""

dataset.groupby("Product")["Product"].count()

"""**Highest sale regarding to each product**"""

dataset.groupby("Product")["Total_Sales"].max()

"""**sorting the maximum sales for each product**"""

dataset.groupby("Product")["Total_Sales"].max().sort_values(ascending=False)

"""**Total Quantity sold for each Product**"""

dataset.groupby("Product")["Quantity"].sum()

dataset.head()

"""**Total sales accomodates**"""

total_amount=dataset["Total_Sales"].sum()
print(total_amount)

"""**Total no of customers in the dataset**"""

no_of_customers=dataset["Customer_ID"].count()
print(no_of_customers)

"""**Total quantity sold **"""

total_quantity=dataset["Quantity"].sum()
print(total_quantity)

"""**The distinct products that we have **"""

print(dataset["Product"].unique())

"""Remodaled dataset without last column total_sales"""

dataset=dataset.drop(columns="total_sales",axis=1)
dataset.head()

"""Final dataset that we have is -"""

dataset